name: Dependabot auto-merge

on:
  workflow_call:
    secrets:
      token:
        description: Privileged GitHub PAT
        required: true
    
jobs:
  setup:
    name: Define matrix
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix}}
    steps:
    - name: Source config
      id: config
      run: |
        config=$(cat .github/dependabot_auto_merge.yml)
        echo "::set-output name=yaml::$config"
        
    - name: Output matrix
      id: matrix
      run: |
        json=${{ toJson(steps.config.outputs.yaml) }}
        echo "::set-output name=matrix::$json"

  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ github.actor == 'dependabot[bot]' }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrx) }}
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: hgdata/dependabot-metadata@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge Dependabot ${{ matrix.ecosystem }} patch releases  
      if: ${{ contains(matrix.types, 'patch') }}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.token }}

    - name: Auto-merge Dependabot ${{ matrix.ecosystem }} minor releases
      if: ${{ contains(matrix.types, 'minor') }}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.token }}
